# Generated by Django 3.2.9 on 2021-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabarruk', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
